//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CaculatePrice")]
    public interface CaculatePrice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CaculatePrice/GetData", ReplyAction="http://tempuri.org/CaculatePrice/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CaculatePrice/GetData", ReplyAction="http://tempuri.org/CaculatePrice/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CaculatePrice/GetTotal", ReplyAction="http://tempuri.org/CaculatePrice/GetTotalResponse")]
        double GetTotal(double subTotal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CaculatePrice/GetTotal", ReplyAction="http://tempuri.org/CaculatePrice/GetTotalResponse")]
        System.Threading.Tasks.Task<double> GetTotalAsync(double subTotal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CaculatePriceChannel : Order.ServiceReference1.CaculatePrice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaculatePriceClient : System.ServiceModel.ClientBase<Order.ServiceReference1.CaculatePrice>, Order.ServiceReference1.CaculatePrice {
        
        public CaculatePriceClient() {
        }
        
        public CaculatePriceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaculatePriceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaculatePriceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaculatePriceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public double GetTotal(double subTotal) {
            return base.Channel.GetTotal(subTotal);
        }
        
        public System.Threading.Tasks.Task<double> GetTotalAsync(double subTotal) {
            return base.Channel.GetTotalAsync(subTotal);
        }
    }
}
